version: 8.0.{build}
os: Visual Studio 2022

environment:
  ASPNETCORE_ENVIRONMENT: appveyor
  COVERALLS_REPO_TOKEN:
    secure: pgM1IhonIH5azWafzyhBUhXFUBA6dbrWf2FxTjlQQ9hfX0A6lkT/ZuaOCJ2drdKm

init:
  - git config --global core.autocrlf input
  - net start MSSQL$SQL2019

services:
  - postgresql

dotnet_csproj:
  patch: true
  file: 'build\version.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}.0'
  file_version: '{version}.0'
  informational_version: '{version}+Branch.$(APPVEYOR_REPO_BRANCH).Sha.$(APPVEYOR_REPO_COMMIT)'

install:
  - dotnet tool install --global coveralls.net

build_script:
  - dotnet pack FluentCommand.sln --configuration Release --include-symbols --include-source

test_script:
  - dotnet test FluentCommand.sln --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*"

after_test:
  - csmacnz.coveralls --useRelativePaths --multiple --input "opencover=test\FluentCommand.Tests\coverage.opencover.xml;opencover=test\FluentCommand.Batch.Tests\coverage.opencover.xml;opencover=test\FluentCommand.SqlServer.Tests\coverage.opencover.xml"

artifacts:
- path: artifacts\*.*nupkg
  name: Packages

deploy:
- provider: Environment
  name: MyGet
