version: 10.0.{build}
os: Visual Studio 2022

environment:
  ASPNETCORE_ENVIRONMENT: appveyor
  COVERALLS_REPO_TOKEN:
    secure: pgM1IhonIH5azWafzyhBUhXFUBA6dbrWf2FxTjlQQ9hfX0A6lkT/ZuaOCJ2drdKm

init:
  - git config --global core.autocrlf input
  - net start MSSQL$SQL2019

services:
  - postgresql

dotnet_csproj:
  patch: true
  file: 'src\Directory.Build.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}.0'
  file_version: '{version}.0'
  informational_version: '{version}+Branch.$(APPVEYOR_REPO_BRANCH).Sha.$(APPVEYOR_REPO_COMMIT)'

install:
  - dotnet tool install --global coveralls.net

build_script:
  - dotnet build FluentCommand.sln --configuration Release
  - dotnet pack FluentCommand.sln --no-build --no-restore --configuration Release --include-symbols --include-source

test_script:
  - dotnet test FluentCommand.sln --configuration Release --collect:"XPlat Code Coverage" --settings coverlet.runsettings

after_test:
  - ps: .\coveralls.ps1

artifacts:
- path: artifacts\*.*nupkg
  name: Packages

deploy:
- provider: Environment
  name: MyGet
